config/routes.rb
Rails.application.routes.draw do
  resources :cats, :users
  resource :session, only: [:new, :create, :destroy]
  
  root "cats#index"
  
  resources :cat_rental_requests do
    member do
      post 'approve'
    end
    
    member do
      post 'deny'
    end
    
  end
  

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  
  CAT_COLORS = %w{black orange red yellow green blue purple calico white}
  
  validates :age, :birth_date, :color, :name, :sex, presence: true
  validates :age, numericality: true
  validates :color, inclusion: {in: CAT_COLORS}
  validates :sex, inclusion: {in: %w{M F}}
  
  has_many :requests, class_name: "CatRentalRequest", dependent: :destroy
  
  def self.colors
    CAT_COLORS
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: { in: %w{PENDING APPROVED DENIED} }
  validates :status, :start_date, :end_date, :cat_id, :user_id, presence: true
  validate :overlapping_approved_requests
  belongs_to :cat
  belongs_to :user
  
  before_validation(on: :create) do
    self.status ||= "PENDING"
  end
  
  def approve!
    self.status = "APPROVED"
    
    ActiveRecord::Base.transaction do
      self.save!
      (overlapping_pending_requests).update_all("status = 'DENIED'")
    end
    self
  end
  
  def deny!
    self.status = "DENIED"
    self.save!
    self
  end
  
  def overlapping_pending_requests
    CatRentalRequest.where("
      NOT ( (TO_DATE (:start, 'yyyy-mm-dd') > end_date) OR
          (start_date > TO_DATE (:last, 'yyyy-mm-dd') ) )
      
      AND cat_id = :cat_id
      
      AND id != :self_id", { start: self.start_date, last: self.end_date, 
                              cat_id: self.cat_id, self_id: self.id } )
  end
  
  def overlapping_approved_requests
    overlapping_approved = overlapping_pending_requests.where("status = 'APPROVED'")

    unless overlapping_approved.empty?
      errors[:base] << "There's an overlapping request!"
    end
  end
    
  def pending?
    self.status == "PENDING"
  end
end

app/models/session_token.rb
class SessionToken < ActiveRecord::Base
  belongs_to :user
  validates :token, :user_id, presence: true
  validates :token, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => { :message => "Password can't be blank"}
  validates :password, :length => { :minimum => 6, allow_nil: true  }
  
  has_many :cats
  has_many :cat_rental_requests
  has_many :session_tokens
  
  before_validation do
    self.session_token ||= User.generate_token
  end
  
  def self.generate_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = User.generate_token
    self.save!
    self.session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    
    user if user.is_password?(password) 
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
  include SessionsHelper

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :owner_check, only: [:approve, :deny]
  before_action :check_login, only: [:create, :new]
  
  def new
    @request = CatRentalRequest.new
  end
  
  def create
    @request = current_user.cat_rental_requests.new(request_params)
    @request.save!
    redirect_to cat_url(@request.cat_id)
  end
  
  def approve
    @request = CatRentalRequest.find(request_params[:id]).approve!
    redirect_to cat_url(@request.cat_id)
  end
  
  def deny
    @request = CatRentalRequest.find(request_params[:id]).deny!
    redirect_to cat_url(@request.cat_id)
  end
  
  private
  
  def owner_check
    if CatRentalRequest.find(request_params[:id]).cat.owner != current_user
      flash[:notice] = "You don't own that cat."
      redirect_to cats_url 
    end
  end

  def request_params
    params.require(:request).permit(:id, :start_date, :end_date)
  end
  
  def check_login
    unless signed_in?
      flash[:notice] = "Not logged in!"
      redirect_to new_session_url
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :owner_check, only: [:edit, :update]
  
  def index
    @cats = Cat.all
  end
  
  def show
    @user_id = current_user.try(:id) || 0
    @cat = Cat.find(params[:id])
  end
  
  def edit
    @cat = Cat.find(params[:id])
  end
  
  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)
    redirect_to cat_url(@cat)
  end
  
  def new
    @cat = Cat.new
  end
  
  def create
    @cat = Cat.create!(cat_params)
    @cat.user_id = current_user.id
    redirect_to cat_url(@cat)
  end
  
  private
  
  def owner_check
    if !current_user || Cat.find(params[:id]).user_id != current_user.id
      flash[:notice] = "You don't own that cat."
      redirect_to cats_url 
    end
  end
  
  def cat_params
    params.require(:cat).permit(:age, :sex, :birth_date, :name, :color)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new]
  
  def new
  end
  
  def create
    @user = User.find_by_credentials(user_params[:user_name], user_params[:password])
    if @user.nil?
      flash.now[:notice] = "Invalid credentials"
      render :new
    else
      sign_in(@user)
      redirect_to cats_url
    end
  end
  
  def destroy
    sign_out!
    redirect_to new_session_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
  
  def redirect_if_logged_in
    if signed_in?
      redirect_to cats_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_logged_in, only: [:new]
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]
    @user.save!
    sign_in(@user)
    redirect_to cats_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
  
  def redirect_logged_in
    if signed_in?
      redirect_to cats_url
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    return nil unless session[:token]
    @current_user ||= SessionToken.find_by_token(session[:token]).user
  end
  
  def sign_in(user)
    @current_user = user
    
    new_token = SessionToken.create!(token: generate_token, user_id: @current_user.id)
    session[:token] = new_token.token
  end
  
  def generate_token
    SecureRandom::urlsafe_base64(16)
  end

  def signed_in?
    current_user.present?
  end
  
  def sign_out!
    current_user.try(:reset_session_token)
    SessionToken.find_by_token(session[:token]).destroy!
    session[:token] = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url%>" method="post">
  <label for="request_select">Cat</label>
  <input name="authenticity_token" 
    type="hidden" 
    value="<%= form_authenticity_token %>" />
  
  <select name="request[cat_id]" id="request_select">
    <option />
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  
  <br><br>
  
  <label for="request_start_date">Start Date</label>
  <input name="request[start_date]" id="request_start_date" type="date">
  
  <br><br>
  
  <label for="request_end_date">End Date</label>
  <input name="request[end_date]" id="request_end_date" type="date">
  
  <br><br>
  <input type="submit" value="Request Cat">
</form>

app/views/cats/_form.html.erb
  <% if @cat.persisted? %>
    <form action="<%= cat_url(@cat)%>" method="post">
  
    <input type="hidden" name="_method" value="PATCH">
  <% else %>
    <form action="<%= cats_url%>" method="post">
  <% end%>
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  
  <label for="cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>">
  
  <br><br>
  
  <label for="cat_age">Age</label>
  <input name="cat[age]" id="cat_age" type="text" value="<%= @cat.age %>">
  
  <br><br>
  
  <label for="cat_birthdate">Birthdate</label>
  <input name="cat[birth_date]" id="cat_birthdate" type="date" value="<%= @cat.birth_date %>">
  
  <br><br>
  
  <label for="cat_sex">Sex</label>
  <select name="cat[sex]">
    <option />
    <option value="M" <%= "selected" if @cat.sex == "M"%>>Male</option>
    <option value="F" <%= "selected" if @cat.sex == "F"%>>Female</option>
  </select>
  
  <br><br>
  
  <label for="color">Color:</label>
  <% Cat.colors.each do |color| %>
  <input type ="radio" name="cat[color]" 
    id="cat_color_<%= color %>" value="<%= color %>" <%= "checked" if @cat.color == color%>>
  <label for="cat_color_<%= color %>"><%= color.capitalize %></label>
  <% end %>
  
  <br><br>
  
  
  
  <input type="submit" value="Update my cat!">
</form>

app/views/cats/edit.html.erb
  <h1>Edit cat</h1>
  
  <%= render partial: "form", object: @cat %>
    
    <br>
    <a href="<%= cats_url %>">Back to index</a>

app/views/cats/index.html.erb
<h1>All cats</h1>
<ul>
  <% @cats.each do |cat| %>
    <li> <a href="<%= cat_url(cat) %>"><%= cat.name %></a> </li>
  <% end %>
</ul>
    
<a href="<%= new_cat_url %>">Make a new cat!</a>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render partial: "form", object: @cat %>

<br>
<a href="<%= cats_url %>">Back to index</a>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
  <table>
    <tr>
      <% @cat.attributes.keys.each do |attribute| %>
        <% next if attribute == "created_at" || attribute == "updated_at" ||
          attribute == "id" %>
  
        <th><%= attribute.gsub("_", " ").capitalize %></th>
      <% end %>
    </tr>
  
    <tr>
      <% @cat.attributes.each do |attribute, value| %>
        <% next if attribute == "created_at" || attribute == "updated_at" ||
              attribute == "id" %>
        <td><%= value %> </td>
      <% end %>
    </tr>
  
  </table>
<br>

<br><br>

<h2>Existing requests:</h2>
<ol>
<% @cat.requests.sort_by(&:start_date).reverse.each do |request| %>
  <li> 
    <%= User.find(request.user_id).user_name %>, 
    <%= request.status %>: <%= request.start_date %>, 
    <%= request.end_date %> 
  </li>
  <% if request.pending? && @cat.owner == current_user %>
  
  <form action="<%= approve_cat_rental_request_url(request) %>" method="post">
    <input type="hidden", name="request[id]" value="<%= request.id %>">
    <input type="submit" value="Approve Request" />
    <input name="authenticity_token" 
      type="hidden" 
      value="<%= form_authenticity_token %>" />
  </form> 
  
  <form action="<%= deny_cat_rental_request_url(request) %>" method="post">
    <input type="hidden", name="request[id]" value="<%= request.id %>">
    <input type="submit" value="Deny Request" />
    <input name="authenticity_token" 
      type="hidden" 
      value="<%= form_authenticity_token %>" />
  </form>
  
  <% end %>
  
<% end %>
</ol>

<a href="<%= cats_url %>">Back to index</a>
<a href="<%= edit_cat_url %>">Edit this cat</a>
<a href="<%= new_cat_rental_request_url %>">Make a new rental request!</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
      <%= flash[:notice] %>
    <br>
    <% if current_user %>
      Welcome, <%= current_user.user_name %>!
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete" />
        <input
           name="authenticity_token"
           type="hidden"
           value="<%= form_authenticity_token %>">
        
        <input type="submit" value="Log out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign in!</a>
      <a href="<%= new_user_url %>">Sign up!</a>
    <% end %>
    <br><br>
    
    <%= yield %>

  </body>
</html>

app/views/users/_form.html.erb
<form action="<%= users_url%>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <label for="user_user_name">User Name</label>
  <input name="user[user_name]" id="user_user_name" type="text" value="<%= @user.user_name %>">

  <br><br>

  <label for="user_password">Password</label>
  <input name="user[password]" id="user_password" type="password" value="<%= @user.password %>">

  <br><br>
  
  <input type="submit" value="Sign me up, Scotty!">
  
</form>

app/views/users/index.html.erb
<h1>All users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.user_name %></li>
  <% end %>
</ul>

<a href="<%= new_user_url %>">Sign up!</a>

app/views/users/new.html.erb
<h1>Add a New User</h1>
  
<%= render partial: "form", object: @user %>

    